databases:
  - name: myportfoliosite
    databaseName: myportfoliosite
    user: myportfoliosite
    region: singapore
    plan: free

services:
  - type: web
    name: myportfoliosite
    env: python
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: './build.sh'
    startCommand: 'python manage.py runserver'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myportfoliosite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true