# Generated by Django 5.0 on 2024-01-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_project_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AddField(
            model_name='project',
            name='big_image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='大画像'),
        ),
        migrations.AddField(
            model_name='project',
            name='small_image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='小画像'),
        ),
    ]
