# Generated by Django 5.0 on 2024-01-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_remove_project_image_url_project_big_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backend',
            field=models.CharField(blank=True, max_length=255, verbose_name='バックエンド'),
        ),
        migrations.AddField(
            model_name='project',
            name='frontend',
            field=models.CharField(blank=True, max_length=255, verbose_name='フロントエンド'),
        ),
        migrations.AlterField(
            model_name='project',
            name='big_image',
            field=models.ImageField(default='', upload_to='', verbose_name='大画像'),
        ),
        migrations.AlterField(
            model_name='project',
            name='small_image',
            field=models.ImageField(default='', upload_to='', verbose_name='小画像'),
        ),
    ]
